/**
 * Cavoke
 * API for cavoke interaction between main server and clients
 *
 * The version of the OpenAPI document: 0.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISessionCreationRequest.h
 *
 * 
 */

#ifndef OAISessionCreationRequest_H
#define OAISessionCreationRequest_H

#include <QJsonObject>

#include "OAIPlayer.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIPlayer;

class OAISessionCreationRequest : public OAIObject {
public:
    OAISessionCreationRequest();
    OAISessionCreationRequest(QString json);
    ~OAISessionCreationRequest() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getGameId() const;
    void setGameId(const QString &game_id);
    bool is_game_id_Set() const;
    bool is_game_id_Valid() const;

    QString getGameConfiguration() const;
    void setGameConfiguration(const QString &game_configuration);
    bool is_game_configuration_Set() const;
    bool is_game_configuration_Valid() const;

    QList<OAIPlayer> getPlayers() const;
    void setPlayers(const QList<OAIPlayer> &players);
    bool is_players_Set() const;
    bool is_players_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString game_id;
    bool m_game_id_isSet;
    bool m_game_id_isValid;

    QString game_configuration;
    bool m_game_configuration_isSet;
    bool m_game_configuration_isValid;

    QList<OAIPlayer> players;
    bool m_players_isSet;
    bool m_players_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISessionCreationRequest)

#endif // OAISessionCreationRequest_H
