/**
 * Cavoke
 * API for cavoke interaction between main server and clients
 *
 * The version of the OpenAPI document: 0.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIUserStatistics.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIUserStatistics::OAIUserStatistics(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIUserStatistics::OAIUserStatistics() {
    this->initializeModel();
}

OAIUserStatistics::~OAIUserStatistics() {}

void OAIUserStatistics::initializeModel() {

    m_total_time_played_sec_isSet = false;
    m_total_time_played_sec_isValid = false;

    m_total_games_played_isSet = false;
    m_total_games_played_isValid = false;
}

void OAIUserStatistics::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIUserStatistics::fromJsonObject(QJsonObject json) {

    m_total_time_played_sec_isValid = ::OpenAPI::fromJsonValue(total_time_played_sec, json[QString("total_time_played_sec")]);
    m_total_time_played_sec_isSet = !json[QString("total_time_played_sec")].isNull() && m_total_time_played_sec_isValid;

    m_total_games_played_isValid = ::OpenAPI::fromJsonValue(total_games_played, json[QString("total_games_played")]);
    m_total_games_played_isSet = !json[QString("total_games_played")].isNull() && m_total_games_played_isValid;
}

QString OAIUserStatistics::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIUserStatistics::asJsonObject() const {
    QJsonObject obj;
    if (m_total_time_played_sec_isSet) {
        obj.insert(QString("total_time_played_sec"), ::OpenAPI::toJsonValue(total_time_played_sec));
    }
    if (m_total_games_played_isSet) {
        obj.insert(QString("total_games_played"), ::OpenAPI::toJsonValue(total_games_played));
    }
    return obj;
}

qint32 OAIUserStatistics::getTotalTimePlayedSec() const {
    return total_time_played_sec;
}
void OAIUserStatistics::setTotalTimePlayedSec(const qint32 &total_time_played_sec) {
    this->total_time_played_sec = total_time_played_sec;
    this->m_total_time_played_sec_isSet = true;
}

bool OAIUserStatistics::is_total_time_played_sec_Set() const{
    return m_total_time_played_sec_isSet;
}

bool OAIUserStatistics::is_total_time_played_sec_Valid() const{
    return m_total_time_played_sec_isValid;
}

qint32 OAIUserStatistics::getTotalGamesPlayed() const {
    return total_games_played;
}
void OAIUserStatistics::setTotalGamesPlayed(const qint32 &total_games_played) {
    this->total_games_played = total_games_played;
    this->m_total_games_played_isSet = true;
}

bool OAIUserStatistics::is_total_games_played_Set() const{
    return m_total_games_played_isSet;
}

bool OAIUserStatistics::is_total_games_played_Valid() const{
    return m_total_games_played_isValid;
}

bool OAIUserStatistics::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_total_time_played_sec_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_total_games_played_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIUserStatistics::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
