/**
 * Cavoke
 * API for cavoke interaction between main server and clients
 *
 * The version of the OpenAPI document: 0.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIUserStatistics.h
 *
 * Statistics on a specific user
 */

#ifndef OAIUserStatistics_H
#define OAIUserStatistics_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIUserStatistics : public OAIObject {
public:
    OAIUserStatistics();
    OAIUserStatistics(QString json);
    ~OAIUserStatistics() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getTotalTimePlayedSec() const;
    void setTotalTimePlayedSec(const qint32 &total_time_played_sec);
    bool is_total_time_played_sec_Set() const;
    bool is_total_time_played_sec_Valid() const;

    qint32 getTotalGamesPlayed() const;
    void setTotalGamesPlayed(const qint32 &total_games_played);
    bool is_total_games_played_Set() const;
    bool is_total_games_played_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 total_time_played_sec;
    bool m_total_time_played_sec_isSet;
    bool m_total_time_played_sec_isValid;

    qint32 total_games_played;
    bool m_total_games_played_isSet;
    bool m_total_games_played_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIUserStatistics)

#endif // OAIUserStatistics_H
