/**
 * Cavoke
 * API for cavoke interaction between main server and clients
 *
 * The version of the OpenAPI document: 0.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIUserGameStatistics.h
 *
 * Statistics on a specific user in a specific game
 */

#ifndef OAIUserGameStatistics_H
#define OAIUserGameStatistics_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIUserGameStatistics : public OAIObject {
public:
    OAIUserGameStatistics();
    OAIUserGameStatistics(QString json);
    ~OAIUserGameStatistics() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getGameId() const;
    void setGameId(const QString &game_id);
    bool is_game_id_Set() const;
    bool is_game_id_Valid() const;

    qint32 getTimePlayedSec() const;
    void setTimePlayedSec(const qint32 &time_played_sec);
    bool is_time_played_sec_Set() const;
    bool is_time_played_sec_Valid() const;

    qint32 getGamesPlayed() const;
    void setGamesPlayed(const qint32 &games_played);
    bool is_games_played_Set() const;
    bool is_games_played_Valid() const;

    double getWinRate() const;
    void setWinRate(const double &win_rate);
    bool is_win_rate_Set() const;
    bool is_win_rate_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString game_id;
    bool m_game_id_isSet;
    bool m_game_id_isValid;

    qint32 time_played_sec;
    bool m_time_played_sec_isSet;
    bool m_time_played_sec_isValid;

    qint32 games_played;
    bool m_games_played_isSet;
    bool m_games_played_isValid;

    double win_rate;
    bool m_win_rate_isSet;
    bool m_win_rate_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIUserGameStatistics)

#endif // OAIUserGameStatistics_H
