name: build-http

on:
  push:
    branches:
      - "master"

jobs:
  build-qt-httpclient:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Qt Http Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: cpp-qt-client
          openapi-file: ${{ env.OAS_FILE }}
      - name: Change Qt5 to Qt with QT_MAJOR_VERSION
        run: sed -i 's;Qt5;Qt${QT_MAJOR_VERSION};g' cpp-qt-client/client/CMakeLists.txt
      - name: Git add & commit
        run: |
          cd cpp-qt-client-client
          git init
          git add -A
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Build Qt Http Client"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH }}
          force: true
          directory: cpp-qt-client-client
env:
  BRANCH: build-httpclient
  OAS_FILE: oas3.yaml