name: build-clients

on:
  push:
    branches:
      - "master"

jobs:
  build-qt-httpclient:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Qt Http Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: cpp-qt-client
          openapi-file: ${{ env.OAS_FILE }}
      - name: Change Qt5 to Qt with QT_MAJOR_VERSION
        run: |
          cd cpp-qt-client-client/client
          perl -pi -e 's;project\(client\);project(openapi);' CMakeLists.txt
          perl -pi -e 's;(?<=find_package\(Qt5Network REQUIRED\));\nfind_package(Qt5Gui REQUIRED)' CMakeLists.txt
          perl -pi -e 's;(?<=Qt5::Network); Qt5::Gui' CMakeLists.txt
          perl -pi -e 's;Qt5;Qt\${QT_MAJOR_VERSION};g' CMakeLists.txt
      - name: Git add & commit
        run: |
          cd cpp-qt-client-client
          git init
          git add -A
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Build Qt Http Client"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build-qt
          force: true
          directory: cpp-qt-client-client
  build-python-httpclient:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Python Http Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: python
          openapi-file: ${{ env.OAS_FILE }}
          config-file: ./.github/files/python-openapi-gen.yml
          generator-tag: v6.0.1
      - name: Git add & commit
        run: |
          cd python-client
          git init
          git add -A
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Build Python Library"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build-python
          force: true
          directory: python-client
env:
  OAS_FILE: oas3.yaml