name: build-http

on:
  push:
    branches:
      - "master"

jobs:
  build-qt-httpclient:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Qt5 Http Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: cpp-qt-client
          openapi-file: ${{ env.OAS_FILE }}
      - name: Git add & commit
        run: |
          git add -A
          git commit -m "Build Qt5 Http Client"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH }}
          force: true
env:
  BRANCH: build-httpclient
  OAS_FILE: oas3.yaml